---
version: '3.4'
services:

  besu_node:
    image: hyperledger/besu:latest
    command: ["--network=kiln",
              "--data-path=/opt/data/el/besu/kiln",
              "--rpc-http-enabled=true",
              "--rpc-http-cors-origins=\"*\"",
              "--host-allowlist=\"*\"",
              "--engine-host-allowlist=\"*\"",
              "--engine-jwt-enabled=true",
              "--engine-rpc-http-port=8550",
              "--engine-rpc-ws-port=8551",
              "--Xmerge-support=true",
              "--engine-jwt-secret=/opt/data/shared/jwtsecret.hex"]

    volumes:
      - ./clients:/opt/data
    ports:
      - "8545:8545"
      - "8550:8550"
      - "8551:8551"
      - "30303:30303/tcp"
      - "30303:30303/udp"

  teku_node:
    environment:
      - "JAVA_OPTS=-Xmx4g"
    image: teku-tsan:latest
    command: ["--network=kiln",
              "--data-base-path=/opt/data/cl/teku/kiln",
              "--Xee-version=kilnv2",
              "--ee-endpoint=http://besu_node:8550",
              "--ee-jwt-secret-file=/opt/data/shared/jwtsecret.hex",
              "--validator-keys=/opt/data/shared/kiln-validator/keys:/opt/data/shared/kiln-validator/passwords",
              "--validator-api-keystore-file=/opt/data/shared/teku_keyapi/teku-keyapi.keystore",
              "--validator-api-keystore-password-file=/opt/data/shared/teku_keyapi/teku-keyapi.password",
              "--validators-proposer-default-fee-recipient=0xFFFFFFF229aEF860fe1d638BD95f14E7025D5Fb1",
              "--p2p-port=9000",
              "--rest-api-enabled=true",
              "--rest-api-docs-enabled=true"]
    depends_on:
      - besu_node
    volumes:
      - ./clients:/opt/data
    ports:
      # Map the p2p port(9000) and REST API port(5051)
      - "9000:9000/tcp"
      - "9000:9000/udp"
      - "5051:5051"
